src/objects/Actor__c.object
<CustomObject>
    <fields>
        <fullName>CountFilms__c</fullName>
        <description>Number of Films starring this Actor.</description>
        <inlineHelpText>Number of Films starring this Actor.</inlineHelpText>
        <label>CountFilms</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Actor</label>
    <nameField>
        <label>Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ActorInFilm__c.object
<CustomObject>
    <description>Connect Film and Actor.</description>
    <fields>
        <fullName>Actor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Actor</label>
        <referenceTo>Actor__c</referenceTo>
        <relationshipLabel>ActorsInFilms</relationshipLabel>
        <relationshipName>ActorsInFilms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Film__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Film</label>
        <referenceTo>Film__c</referenceTo>
        <relationshipLabel>ActorsInFilms</relationshipLabel>
        <relationshipName>ActorsInFilms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ActorInFilm</label>
    <nameField>
        <displayFormat>AF-{00000000}</displayFormat>
        <label>ActorInFilm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActorsInFilms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Film__c.object
<CustomObject>
    <description>Сontains movie information.</description>
    <label>Film</label>
    <nameField>
        <label>Film Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Films</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActorInFilmTriggerTest.cls
/**
 * Created by User on 11.01.2020.
 */

@IsTest
private class ActorInFilmTriggerTest {

    @testSetup
    static void testSetup() {
        List<Film__c> films = new List<Film__c>();
        List<Actor__c> actors = new List<Actor__c>();

        for (Integer i = 0; i < 10; i++) {
            films.add(new Film__c(Name = 'TestFilm_' + i));
        }
        for (Integer i = 0; i < 10; i++) {
            actors.add(new Actor__c(Name = 'TestActorName_' + i));
        }
        insert films;
        insert actors;
    }

    @isTest
    static void testInsertBehavior() {
        List<ActorInFilm__c> actorInFilms = new List<ActorInFilm__c>();
        List<ActorInFilm__c> newActorInFilms = new List<ActorInFilm__c>();
        List<Film__c> films = new List<Film__c>();
        List<Actor__c> actors = new List<Actor__c>();
        Integer numberOfFilms = 0;
        Integer numberOfNewActorFilms = 0;

        films = [
                SELECT Name
                FROM Film__c
        ];
        actors = [
                SELECT Name
                FROM Actor__c
                ORDER BY Name
        ];
        for (Integer i = 0; i < 10; i++) {
            actorInFilms.add(new ActorInFilm__c(Film__c = films[i].Id, Actor__c = actors[i].Id));
        }
        numberOfFilms++;
        for (Integer i = 0; i < 9; i++) {
            actorInFilms.add(new ActorInFilm__c(Film__c = films[i+1].Id, Actor__c = actors[i].Id));
        }
        numberOfFilms++;
        Actor__c newActor = new Actor__c(Name = 'QQNewActorName');
        insert newActor;
        for (Integer i = 0; i < 5; i++) {
            actorInFilms.add(new ActorInFilm__c(Film__c = films[i].Id, Actor__c = newActor.Id));
            numberOfNewActorFilms++;
        }
        Test.startTest();
        insert actorInFilms;
        for (Integer i = 5; i < 10; i++) {
            newActorInFilms.add(new ActorInFilm__c(Film__c = films[i].Id, Actor__c = newActor.Id));
            numberOfNewActorFilms++;
        }
        insert newActorInFilms;
        Test.stopTest();

        System.assertEquals([
                SELECT Name, CountFilms__c
                FROM Actor__c
                WHERE Name LIKE 'Test%'
                ORDER BY Name ASC
                LIMIT 1
        ].CountFilms__c, numberOfFilms);
        System.assertEquals([
                SELECT Name, CountFilms__c
                FROM Actor__c
                WHERE Name LIKE 'QQNewActorName'
        ].CountFilms__c, numberOfNewActorFilms);
    }

    @isTest
    static void testDeleteBehavior() {
        List<ActorInFilm__c> actorInFilms = new List<ActorInFilm__c>();
        List<Film__c> films = new List<Film__c>();
        List<Actor__c> actors = new List<Actor__c>();
        Integer numberOfFilms = 0;

        films = [
                SELECT Name
                FROM Film__c
        ];
        actors = [
                SELECT Name
                FROM Actor__c
                ORDER BY Name
        ];
        for (Integer i = 0; i < 10; i++) {
            actorInFilms.add(new ActorInFilm__c(Film__c = films[i].Id, Actor__c = actors[i].Id));
        }
        numberOfFilms++;
        insert actorInFilms;

        Test.startTest();
        delete actorInFilms;
        Integer numberOfFilmsAfterDelete = --numberOfFilms;
        Test.stopTest();

        System.assertEquals([
                SELECT Name, CountFilms__c
                FROM Actor__c
                WHERE Name LIKE 'Test%'
                ORDER BY Name ASC
                LIMIT 1
        ].CountFilms__c, numberOfFilmsAfterDelete);

    }
}