src/objects/Actor__c.object
<CustomObject>
    <fields>
        <fullName>CountFilms__c</fullName>
        <description>Number of Films starring this Actor.</description>
        <inlineHelpText>Number of Films starring this Actor.</inlineHelpText>
        <label>CountFilms</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Actor</label>
    <nameField>
        <label>Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ActorInFilm__c.object
<CustomObject>
    <description>Connect Film and Actor.</description>
    <fields>
        <fullName>Actor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Actor</label>
        <referenceTo>Actor__c</referenceTo>
        <relationshipLabel>ActorsInFilms</relationshipLabel>
        <relationshipName>ActorsInFilms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ActorInFilm</label>
    <nameField>
        <displayFormat>AF-{00000000}</displayFormat>
        <label>ActorInFilm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActorsInFilms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActorInFilmTriggerHandler.cls
/**
 * Created by User on 10.01.2020.
 */

public with sharing class ActorInFilmTriggerHandler {
    public void updateCountFilmsOnActor(List<ActorInFilm__c> actorsInFilms) {
        Map<Id, Integer> actorCounter = new Map<Id, Integer>();
        List<Id> actorsIds = new List<Id>();
        List<Actor__c> actors = new List<Actor__c>();

        for (ActorInFilm__c actorInFilm : actorsInFilms) {
            actorsIds.add(actorInFilm.Actor__c);
            if (actorCounter.get(actorInFilm.Actor__c) == null) {
                actorCounter.put(actorInFilm.Actor__c,1);
            } else {
                actorCounter.put(actorInFilm.Actor__c, actorCounter.get(actorInFilm.Actor__c)+1);
            }
        }
        actors = [
                SELECT Name, CountFilms__c
                FROM Actor__c
                WHERE Id IN :actorsIds
        ];
        if (Trigger.isDelete && Trigger.isAfter) {
            for (Actor__c actor : actors) {
                if (actor.CountFilms__c != null && actor.CountFilms__c > 0) {
                    actor.CountFilms__c -= actorCounter.get(actor.Id);
                }
            }
        } else if (Trigger.isInsert && Trigger.isAfter) {
            for (Actor__c actor : actors) {
                if (actor.CountFilms__c == null) {
                    actor.CountFilms__c = actorCounter.get(actor.Id);
                } else {
                    actor.CountFilms__c += actorCounter.get(actor.Id);
                }
            }
        }
        update actors;
    }
}